name: Binary Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  binary:
    name: binary build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: rolling, ROS_REPO: main}
          - {ROS_DISTRO: rolling, ROS_REPO: testing}
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
